### PR TITLE
[feature] History file

### PR DESCRIPTION
**Pull request by poying**
To configure history options in .rc file:

```bash
export FANYI_ENABLE_HISTORY=1
export FANYI_HISTORY_FILE_PATH='~/.fanyi_history'
export FANYI_HISTORY_FILE_SIZE=1000 # 1000 lines
```

### CODE REVIEW

**Comment by afc163** [comment]
For what?

**Comment by poying** [comment]
For instance, we can find out what we translated in the past few days, it is really helpful to english learning.

**Comment by afc163** [comment]
`history | grep '  fanyi'` is enough ?

**Comment by poying** [comment]
Yep, that is enough. :sweat_smile:

**Comment by afc163** [comment]
Thx all the same :smile:

**Pull request closed without merging**
